sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "l#z51198209psql"
  alioss:
    endpoint: oss-ap-southeast-1.aliyuncs.com
    access-key-id: LTAI5tC4DE2NAbaSM92e1iE1
    access-key-secret: XuUHWeg5apxMKJOcHHz5TopuGJ6Olw
    bucket-name: lvshrd
  redis:
    host: localhost
    port: 6379
    database: 1
#    database默认DB0
#    password:

  wechat:
    appid: wx7de0883668a3a580
    secret: 529a28960e662080ab4b3d851e9a433f